package com.changent.barrenlandanalysis

import groovy.transform.TupleConstructor

/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'worldwidewilly' at '10/1/16 7:54 AM' with Gradle 2.14.1
 *
 * @author worldwidewilly, @date 10/1/16 7:54 AM
 */

class BarrenLandAnalysis {
    final int width
    final int height

    public BarrenLandAnalysis() {
        width = 400
        height = 600
    }

    public BarrenLandAnalysis(int width, int height) {
        this.width = width
        this.height = height
    }

    public static void main(String... args) {

        def barrenLandAnalysis = BarrenLandAnalysis()

        def parsed = barrenLandAnalysis.parseCommandLine(new Scanner(System.in), System.out)

        if (parsed) {
            // do work
        }

    }
}
