package com.changent.barrenlandanalysis

import groovy.transform.TupleConstructor

/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'worldwidewilly' at '10/1/16 7:54 AM' with Gradle 2.14.1
 *
 * @author worldwidewilly, @date 10/1/16 7:54 AM
 */

import spock.lang.Specification

class BarrenLandAnalysisTest extends Specification {
    def "creating with default width and height"() {
        when:
        BarrenLandAnalysis barrenLandAnalysis = new BarrenLandAnalysis()

        then:
        barrenLandAnalysis.width == 400
        barrenLandAnalysis.height == 600
    }

    def "creating with specific width and height"() {
        when:
        BarrenLandAnalysis barrenLandAnalysis = new BarrenLandAnalysis(100, 200)

        then:
        barrenLandAnalysis.width == 100
        barrenLandAnalysis.height == 200
    }

    def "handles no barren land definitions"() {
        given:
        def command = ''
        def sysin = new Scanner(new StringReader(command))
        def sysout = new ByteArrayOutputStream()
        BarrenLandAnalysis barrenLandAnalysis = new BarrenLandAnalysis()

        when:
        def result = barrenLandAnalysis.parseCommandLine(sysin, new PrintStream(sysout))

        then:
        result == [[]]
    }

    def "handles one barren land definitions"() {
        given:
        def command = '0 292 399 307'
        def sysin = new Scanner(new StringReader(command))
        def sysout = new ByteArrayOutputStream()
        BarrenLandAnalysis barrenLandAnalysis = new BarrenLandAnalysis()

        when:
        def result = barrenLandAnalysis.parseCommandLine(sysin, new PrintStream(sysout))

        then:
        result == [['0', '292', '399', '307']]
        result == [[0, 292, 399, 307]]
    }
}
